### ISSUE TITLE
Module 'flutter_secure_storage' not found

### ISSUE THREAD

**Issue by newbieflutter** [juliansteenbakker/flutter_secure_storage#299]
Hi,
   I am using the latest version 4.2.1. But on my ios I keep getting this error Module 'flutter_secure_storage' not found ? What should I do to overcome this ?

**Comment by juliansteenbakker** [comment]
Can you try using the latest beta version? 5.0.0-beta.4

**Comment by wjbladek** [comment]
I have the same issue on both 4.2.1 and 5.0.0-beta.4. Adding flutter_secure_storage to the project leads to failed build with error 
```
.../GeneratedPluginRegistrant.m:12:9: fatal error: module 'flutter_secure_storage' not found
    @import flutter_secure_storage;
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
Could not build the precompiled application for the device.
```
I'm on channel beta, 2.4.0-4.2.pre.

**Comment by adeblas** [comment]
Same problem here. You can run, debug and build from  flutter command line, but not from XCode.
Tried even to create a new project from scratch with the same outcome.

Running on Mac M1 XCode 

**This is Flutter Doctor:**

 No issues found!
adeblas@MacBook-Air-M1 bin % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale es-ES)
    • Flutter version 2.5.3 at /Users/adeblas/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (hace 5 semanas), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/adeblas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.63.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 95343FDB-8026-487E-940D-1CF4B73E7F8B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

**Comment by BBoltzmann** [comment]
Same problem here

**Comment by VCasecnikovs** [comment]
Same problem here

**Comment by FERNANDO1307Q** [comment]
Same problem

**Comment by zliebersbach** [comment]
Same problem

**Comment by fabien79** [comment]
In Xcode, update your IOS deployment target to at least 12, and it should fix the probleme

**Comment by fluttertests** [comment]
I had same error, this one is worked for me: https://github.com/mogol/flutter_secure_storage/issues/57#issuecomment-498715533

**Comment by Hectorc70** [comment]
> Tuve el mismo error, este me funcionó: [# 57 (comentario)](https://github.com/mogol/flutter_secure_storage/issues/57#issuecomment-498715533)

me funciono

**Comment by Aruljebaraj** [comment]
.../GeneratedPluginRegistrant.m:12:9: fatal error: module 'flutter_secure_storage' not found
    @import flutter_secure_storage;
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete




Facing same issue in CI/CD 
tried 
flutter clean
flutter pub get
pod deintegrate 
pod install
