### ISSUE TITLE
PlatformException(Unexpected security result code, Code: -25299, Message: The specified item already exists in the keychain., -25299, null)

### ISSUE THREAD

**Issue by suhailbilalw** [juliansteenbakker/flutter_secure_storage#835]
Can anybody let me know what could be possible fix for the issue.
Platform: iOS; Flutter Secure Storage version: 9.2.2

`message_codecs.dart in StandardMethodCodec.decodeEnvelope at line 648 within flutter`
`platform_channel.dart in MethodChannel._invokeMethod at line 334 within flutter`
`flutter_secure_storage.dart in FlutterSecureStorage.write at line 114 within flutter_secure_storage`

**Comment by SincerelyFaust** [comment]
I am experiencing the same issue.

**Comment by suhailbilalw** [comment]
I have made little progress:

`
        const iOptions = IOSOptions(
            accessibility: KeychainAccessibility.first_unlock_this_device);
        try {
          await write(key: key, value: value, iOptions: iOptions);
        } on PlatformException catch (e) {
          if (e.message ==
              "Code: -25299, Message: The specified item already exists in the keychain.") {
              await delete(key: key, iOptions: iOptions);
              await write(key: key, value: value, iOptions: iOptions);
           }
`
Until now it seems working.

**Comment by suhailbilalw** [comment]
I tried to clear the existing value before overwriting it didn't work.

**Comment by suhailbilalw** [comment]
This issue happens when we have data already in the keychain with the same key using but with different accessibility mode. delete the key the key in that accessibility mode and then try writing again in this mode, that will resolve this issue.

**Comment by gopelkujo** [comment]
I experienced this, but i don't understand about delete key in specific mode. Because i didn't modify any option, i left it default. Can explain it or with example?

**Comment by trueAtom** [comment]
Flutter (Channel stable, 3.27.4) flutter_secure_storage: ^9.2.4

@singleton
FlutterSecureStorage get flutterSecureStorage => const FlutterSecureStorage();

OS version: iosiOS 17.6.1
Model:iPhone 11

0x0 FlutterSecureStorage.write + 114 (flutter_secure_storage.dart:114)

PlatformException(Unexpected security result code, Code: -25299, Message: The specified item already exists in the keychain., -25299, null)

Is the problem still relevant?

**Comment by dimas-ibnu** [comment]
im still facing the same issue

**Comment by Vukan-Levi9** [comment]
@juliansteenbakker I'm still facing the issue in the v10 version.
