### ISSUE TITLE
iOS restore app from backup

### ISSUE THREAD

**Issue by pdefuns** [juliansteenbakker/flutter_secure_storage#88]
When I'm restoring our app from an existing backup, all the data is still there.
Is there a possibility to disable storing this data in the cloud and only store it on the phone itself?

Best would be if the stored data is only valid for this explicit installation of the app.
If I uninstall the app and install it again, the data is still there.

Thanks!

**Comment by MoyaMaker** [comment]
I'm haveing the same problem when we uninstall the app and install again, the data is still there.

**Comment by chriswellingsfairsailcom** [comment]
I think that's due to iOS Keychain's behaviour of not deleting the KeyChain item on delete of the app: https://forums.developer.apple.com/message/112523#112523 (this post is old however this one seems to suggest the behaviour has not changed: https://forums.developer.apple.com/thread/122490)

A potential solution could be the clearing of the Keychain on re-install: https://forums.developer.apple.com/thread/15409 and https://stackoverflow.com/questions/4747404/delete-keychain-items-when-an-app-is-uninstalled

**Comment by LOG-TAG** [comment]
```
let userDefaults = UserDefaults.standard

if !userDefaults.bool(forKey: "hasRunBefore") {
     // Remove Keychain items here

     // Update the flag indicator
     userDefaults.set(true, forKey: "hasRunBefore")
}
```

what is the Remove Keychain code ? and we can't pass user default code flag to flutter main method?and clear the data in flutter main method ?

**Comment by mogol** [comment]
You need do use a storage that is removed when the app is uninstalled and not restored from backup. 

To store "hasRunBefore" you can use https://pub.dev/packages/shared_preferences or any file in temp directory.
 To delete everything from secure storage, you can use  [deleteAll](https://pub.dev/documentation/flutter_secure_storage/latest/flutter_secure_storage/FlutterSecureStorage/deleteAll.html)

**Comment by umaqs** [comment]
something like this:

```
clearSecureStorageOnReinstall() async {
    String key = 'hasRunBefore';
    SharedPreferences prefs = await SharedPreferences.getInstance();

    if(!prefs.getBool(key)) {
      FlutterSecureStorage storage = FlutterSecureStorage();
      await storage.deleteAll();
      prefs.setBool(key, true);
    }
  }
```

**Comment by YAPPDEF** [comment]
@mogol we did a workaround solution like that (create a file and check for existence)

Is it really wanted that everyone needs to implements this instead of adding it to the plugin itself? Storing data in cloud shouldn't be the default option..

**Comment by mogol** [comment]
@YAPPDEF it’s default system behavior. As the package as a thin wrapper, the package inherits this behavior. 

You can generalize your solution and contribute to the package

**Comment by yogithesymbian** [comment]
> something like this:
> 
> ```
> clearSecureStorageOnReinstall() async {
>     String key = 'hasRunBefore';
>     SharedPreferences prefs = await SharedPreferences.getInstance();
> 
>     if(!prefs.getBool(key)) {
>       FlutterSecureStorage storage = FlutterSecureStorage();
>       await storage.deleteAll();
>       prefs.setBool(key, true);
>     }
>   }
> ```

please more describe when these code i need to trigger ?

**Comment by hpelitebook745G2** [comment]
@umaqs @sotheasdc how does this work for you? I tried it, but to uninstall the app on macOS, you need to delete the app in the /Applications folder. However, this doesn't clear the SharedPreferences, so I always get `hasRunBefore` as `true`.
